include("${CMAKE_CURRENT_LIST_DIR}/CxBaseLibTargets.cmake")

get_target_property(IMP_CONFIGS_PROP AT::CxBaseLib IMPORTED_CONFIGURATIONS)

message("IMPORTED_CONFIGURATIONS: ${IMP_CONFIGS_PROP}")

list (FIND IMP_CONFIGS_PROP "DEBUG" _index)
get_target_property(IMPORTED_IMPLIB_VALUE AT::CxBaseLib IMPORTED_IMPLIB_DEBUG)
get_target_property(IMPORTED_LOCATION_VALUE AT::CxBaseLib IMPORTED_LOCATION_DEBUG)
if((_index EQUAL -1) OR ((NOT EXISTS "${IMPORTED_IMPLIB_VALUE}") AND (NOT EXISTS "${IMPORTED_LOCATION_VALUE}")))
	set_target_properties(AT::CxBaseLib PROPERTIES
	  MAP_IMPORTED_CONFIG_DEBUG Release
	)
endif()
unset(IMPORTED_IMPLIB_VALUE)

list (FIND IMP_CONFIGS_PROP "MINSIZEREL" _index)
get_target_property(IMPORTED_IMPLIB_VALUE AT::CxBaseLib IMPORTED_IMPLIB_MINSIZEREL)
get_target_property(IMPORTED_LOCATION_VALUE AT::CxBaseLib IMPORTED_LOCATION_MINSIZEREL)
if((_index EQUAL -1) OR ((NOT EXISTS "${IMPORTED_IMPLIB_VALUE}") AND (NOT EXISTS "${IMPORTED_LOCATION_VALUE}")))
	set_target_properties(AT::CxBaseLib PROPERTIES
	  MAP_IMPORTED_CONFIG_MINSIZEREL Release
	)
endif()
unset(IMPORTED_IMPLIB_VALUE)

list (FIND IMP_CONFIGS_PROP "RELWITHDEBINFO" _index)
get_target_property(IMPORTED_IMPLIB_VALUE AT::CxBaseLib IMPORTED_IMPLIB_RELWITHDEBINFO)
get_target_property(IMPORTED_LOCATION_VALUE AT::CxBaseLib IMPORTED_LOCATION_RELWITHDEBINFO)
if((_index EQUAL -1) OR ((NOT EXISTS "${IMPORTED_IMPLIB_VALUE}") AND (NOT EXISTS "${IMPORTED_LOCATION_VALUE}")))
	set_target_properties(AT::CxBaseLib PROPERTIES
	  MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
	)
endif()
unset(IMPORTED_IMPLIB_VALUE)

UNSET(IMP_CONFIGS_PROP)
